# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Tests

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Get Version from Tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build Application
      run: go build -ldflags="-X main.Version=${VERSION}" -o bin/template-dockerfiles ./cmd/template-dockerfiles

    - name: Upload Release Binary
      uses: actions/upload-artifact@v3
      with:
        name: template-dockerfiles
        path: bin/template-dockerfiles
